Repository wnsxor1993/swift-starbucks, pull requests merged in 2022-05, with the labels that each got.

#4 화면 흐름 구성
  Starbucks/Starbucks.xcodeproj/project.pbxproj
  Starbucks/Starbucks/Assets.xcassets/AppIcon.appiconset/Contents.json
  Starbucks/Starbucks/Base.lproj/Main.storyboard
  Starbucks/Starbucks/SceneDelegate.swift
  Starbucks/Starbucks/ViewController.swift
  Starbucks/Starbucks/ViewController/ContainerViewController.swift
  Starbucks/Starbucks/ViewController/HomeViewController.swift
  Starbucks/Starbucks/starbucksEventImage.png
Labels: feature

#6 초기 이벤트 화면 구현
  Starbucks/Starbucks.xcodeproj/project.pbxproj
  Starbucks/Starbucks/AppDelegate.swift
  Starbucks/Starbucks/Base.lproj/Main.storyboard
  Starbucks/Starbucks/Model/Event.swift
  Starbucks/Starbucks/SceneDelegate.swift
  Starbucks/Starbucks/ViewController/ContainerViewController.swift
  Starbucks/Starbucks/ViewController/EventViewController.swift
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: feature

#7 초기 이벤트 화면 리팩토링
  Starbucks/Starbucks.xcodeproj/project.pbxproj
  Starbucks/Starbucks/AppDelegate.swift
  Starbucks/Starbucks/Base.lproj/Main.storyboard
  Starbucks/Starbucks/Model/Event.swift
  Starbucks/Starbucks/Model/EventDataManager.swift
  Starbucks/Starbucks/ViewController/ContainerViewController.swift
  Starbucks/Starbucks/ViewController/EventViewController.swift
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: refactor

#9 이벤트 화면 호출 로직 리팩토링
  Starbucks/Starbucks.xcodeproj/project.pbxproj
  Starbucks/Starbucks/AppDelegate.swift
  Starbucks/Starbucks/JSONConverter.swift
  Starbucks/Starbucks/Model/DataManager.swift
  Starbucks/Starbucks/Model/EventDataManager.swift
  Starbucks/Starbucks/URLConnector.swift
  Starbucks/Starbucks/ViewController/ContainerViewController.swift
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: refactor

#10 HomeView compositionLayout 기본구조, EventModal Fix
  Starbucks/Starbucks.xcodeproj/project.pbxproj
  Starbucks/Starbucks/Base.lproj/Main.storyboard
  Starbucks/Starbucks/SceneDelegate.swift
  Starbucks/Starbucks/View/CollectionHeaderView.swift
  Starbucks/Starbucks/View/CollectionViewController.xib
  Starbucks/Starbucks/View/RecommendItemCollectionViewCell.swift
  Starbucks/Starbucks/View/RecommendItemCollectionViewCell.xib
  Starbucks/Starbucks/View/TableViewCell.swift
  Starbucks/Starbucks/ViewController/CollectionViewController.swift
  Starbucks/Starbucks/ViewController/EventViewController.swift
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: feature, fix

#12 fix merge conflict
  Starbucks/Starbucks/ViewController/ContainerViewController.swift
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: fix

#18 HomeView API 통신 [ mainEvent 데이터 ]
  Starbucks/Starbucks/JSONConverter.swift
  Starbucks/Starbucks/Model/HomeViewDataManager.swift
  Starbucks/Starbucks/View/MainEventCell.xib
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: feature

#20 Recommand 이미지 캐싱 작업 처리
  Starbucks/Starbucks.xcodeproj/project.pbxproj
  Starbucks/Starbucks/ImageCacheManager.swift
  Starbucks/Starbucks/Model/HomeViewDataManager.swift
Labels: feature

#22 homeView 셀 데이터 초기화 작업 및 셀 테두리 작업
  Starbucks/Starbucks/View/CollectionHeaderView.swift
  Starbucks/Starbucks/View/RecommendItemCollectionViewCell.swift
  Starbucks/Starbucks/View/RecommendItemCollectionViewCell.xib
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: feature, fix

#23 HomeView API 통신 [ nowRecommand 데이터 ]
  Starbucks/Starbucks/Base.lproj/Main.storyboard
  Starbucks/Starbucks/Model/HomeViewDataManager.swift
  Starbucks/Starbucks/View/RecommendItemCollectionViewCell.swift
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: feature

#24 HomeView Refactoring, Username 뷰에 반영
  Starbucks/Starbucks/View/CollectionHeaderView.swift
  Starbucks/Starbucks/ViewController/HomeViewController.swift
Labels: feature, refactor
